# Import Library

In [39]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [40]:
import sys
import warnings
from pathlib import Path

warnings.filterwarnings('ignore')

cwd = Path.cwd().resolve()
ROOT = next(p for p in [cwd, *cwd.parents] if (p / 'scripts').is_dir())
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
print('Root repo:', ROOT)

Root repo: C:\Users\Kiranna\OneDrive\Documents\VS Code\Structural Damage Classification

In [41]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scripts.preprocess import ID_COL, TARGET_COL, MODEL_PATH, load_data
from scripts.feature_engineering import build_features
from scripts.predict import (
    load_model,
    labels_to_numeric,
    build_submission,
    validate_submission,
    save_submission,
)

sns.set_theme(style='whitegrid')

# Import Model dan Data

In [42]:
model = load_model()
test = load_data('test.csv')
sample_submission = load_data('sample_submission.csv')

print('Model                  :', MODEL_PATH.name)
print('Test shape             :', test.shape)
print('Sample submission shape:', sample_submission.shape)

Model                  : pipeline_model_rf.pkl
Test shape             : (228629, 16)
Sample submission shape: (228629, 2)

# Data Cleaning

In [43]:
print('age_building == 999 di test sebelum cleaning:', (test['age_building'] == 999).sum())

X_test = build_features(test)

print('NaN age_building sesudah cleaning            :', X_test['age_building'].isna().sum())
print('X_test shape:', X_test.shape)

age_building == 999 di test sebelum cleaning: 946
NaN age_building sesudah cleaning            : 946
X_test shape: (228629, 15)

# Submission

In [44]:
submission = build_submission(model, test)
submission.head()

    building_id  damage_grade
0  122207000141             2
1  284909000871             5
2  241904000231             3
3  248308000891             3
4  300405002981             5

In [45]:
path = save_submission(submission)
print(f'Submission tersimpan di: {path} ({len(submission)} baris)')

Submission tersimpan di: C:\Users\Kiranna\OneDrive\Documents\VS Code\Structural Damage Classification\submissions\submission.csv (228629 baris)

In [46]:
pd.read_csv(path).head()

    building_id  damage_grade
0  122207000141             2
1  284909000871             5
2  241904000231             3
3  248308000891             3
4  300405002981             5